### ISSUE TITLE
Android To-Do list

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/react-native-aztec#4]
This is the first master thread / TODO list for Android.

- [ ] The "HTML" editor is blank. It seems to me that is not properly drawn/layout'ed on the screen. We should also resize the whole component accordingly. Since switching from visual to HTML will change the size of the whole component.
- [ ] Re-structuring to make this an actual React Native library, by following the structure here https://github.com/wordpress-mobile/react-native-recyclerview-list
- [ ] Example app with basic structure (See above)
- [ ] Check the following warning in console
`W/unknown:ReactNative: Attempt to set local data for view with unknown tag: 2131230754`
It seems to be logged when we set the content of the visual editor. It should not be there.
- [ ] The toolbar should be moved on the top of the view and kept there when the component grows. Maybe it's just a matter of adding passing to AztecText and properly place the toolbar there.  At least for now. Proper design will follow.
- [ ] Do no hardcore toolbar high in code. Read the value from values and use it. 

- [ ] Add resizing behavior? 
- [ ] Make a consisted list of props for both iOS and Android
